title: "Wenhui Li"
author: "Wenhui Li"
description: "Indiana University Bloomington"
permalink: /:title/
lang: "en"
excerpt_separator: "<!--more-->"
date_format: "%B %d, %Y"

collections:
  research:
    output: true
    permalink: /research/:name/

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", url: "https://wenhuili324.github.io/CV_Wenhui.pdf"}
  - {file: "research.md", title: "Research Projects"}
  - {file: "blog.md", title: "Life & Moments"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:wenhuili324@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/wenhuili324"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/wenhui-li-58ba85201/"}
  - {title: Google Scholar, icon: google, url: "https://scholar.google.com/citations?user=zIo3NqEAAAAJ&hl=en"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
